from django.contrib.auth import views as auth_views
from django.urls import path

from mase.mase import views

urlpatterns = [
    path('login/', auth_views.login, name="connexion"),
    path('logout/', auth_views.logout, {'next_page' : '/login/'}, name="deconnexion"),

    #password reset urls
    path('password_reset/', auth_views.password_reset, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', auth_views.password_reset_complete, name='password_reset_complete'),
]

#vues communes
urlpatterns += [
    path('accueil/', views.home, name="home"),
    path('', views.home, name="home"),
    path('mase/presentation/', views.presentation, name="presentation"),
    path('mase/historique/', views.historique, name="historique"),
    path('mase/processus_de_certification/', views.certification, name="certification"),
    path('mase_senegal/', views.maseSenegal, name="maseSenegal"),
    path('mase_senegal/adhesions', views.AdhesionCreate.as_view(), name="adhesions"),
    path('mase_senegal/veille_reglementaire/', views.veille_reglementaire, name="veille_reglementaire"),
    path('mase_senegal/cabinet/', views.cabinets_audit, name="cabinets"),
    path('mase_senegal/centres_formations/', views.centres_formations, name="centres_formations"),
    path('activites', views.activites, name="activites"),
    path('contact/', views.contact, name="contact"),
    #path('entite/liste/', views.EntiteList.as_view(), name="liste_entites"),
    #path('entite/detail/<slug>/', views.EntiteDetail.as_view(), name="detail_entite"),
    #path('entite/modifier/<slug>/', views.EntiteUpdate.as_view(), name="modifier_entite"),
    #path('entite/effacer/<slug>/', views.EntiteDelete.as_view(), name="effacer_entite"),
    path('entite/desactiver/<slug>/', views.desactiver_entite, name="desactiver_entite"),
    path('entite/reactiver/<slug>/', views.reactiver_entite, name="reactiver_entite"),
    path('activation/<uidb64>/<token>/', views.activation_compte, name='activate'),
    path('formations/liste/', views.FormationList.as_view(), name='liste_formations'),
    path('formation/detail/<slug>/', views.FormationDetail.as_view(), name="detail_formation"),
    path('organismes/liste/', views.OrganismeFormationList.as_view(), name='liste_organismes'),
    path('organisme/detail/<slug>/', views.OrganismeFormationDetail.as_view(), name='detail_organisme'),
    path('formateurs/liste/', views.FormateurList.as_view(), name="liste_formateurs"),
    path('formateur/modifier/<slug>/', views.FormateurUpdate.as_view(), name="modifier_formateur"),
    path('formateur/detail/<slug>/', views.FormateurDetail.as_view(), name="detail_formateur"),
    path('entreprises/intervenantes/liste/', views.EntrepriseIntList.as_view(), name="liste_entreprises_interv"),
    path('entreprises/intervenantes/detail/<slug>/', views.EntrepriseIntDetail.as_view(), name="detail_entreprise_interv"),
    path('intervenants/liste/', views.IntervenantList.as_view(), name="liste_intervenants"),
    path('intervenant/detail/<slug>/', views.IntervenantDetail.as_view(), name="detail_intervenant"),
    path('entreprises/utilisatrices/liste/', views.EntrepriseUtilList.as_view(), name="liste_entreprises_util"),
    path('entreprises/utilisatrices/detail/<slug>/', views.EntrepriseUtilDetail.as_view(), name="detail_entreprise_util"),
    path('evenements/liste/', views.EvenementListe.as_view(), name="liste_events"),
    path('evenements/detail/<slug>/', views.EvenementDetail.as_view(), name="detail_event"),
    path('documents/liste/', views.DocumentListe.as_view(), name="liste_documents"),
    path('ajax/utilisateurs/liste', views.AjaxUtilisateur.as_view(), name="ajax_utilisateurs"),
    path('modifier_password/', auth_views.password_change, name="change_password"),
    path('modifier_password_ok/', auth_views.password_change_done, name="password_change_done"),
    path('mon_organisme/', views.MonOrganismeFormation.as_view(), name="mon_organisme"),
    path('modifier/mon_organisme/', views.ModifierMonOrganismeFormation.as_view(), name="modifier_mon_organisme"),
    path('mon_ei/', views.MonEI.as_view(), name="mon_ei"),
    path('modifier/mon_ei/', views.ModifierMonEI.as_view(), name="modifier_mon_ei"),
    path('mon_eu/', views.MonEU.as_view(), name="mon_eu"),
    path('modifier/mon_eu/', views.ModifierMonEU.as_view(), name="modifier_mon_eu"),
    path('formateur/ajouter/of', views.FormateurCreateOF.as_view(), name="ajouter_formateur_of"),
    path('mon_profil/', views.MonProfil.as_view(), name="mon_profil"),

]

#vues_administrateur
urlpatterns += [
    #path('entite/creer/', views.EntiteCreate.as_view(), name="ajouter_entite"),
    path('formation/creer/', views.FormationCreate.as_view(), name="ajouter_formation"),
    path('formation/modifier/<slug>/', views.FormationUpdate.as_view(), name="modifier_formation"),
    path('formation/supprimer/<slug>/', views.FormationDelete.as_view(), name="supprimer_formation"),
    path('organisme/creer/', views.OrganismeFormationCreate.as_view(), name="ajouter_organisme"),
    path('organisme/modifier/<slug>/', views.OrganismeFormationUpdate.as_view(), name="modifier_organisme"),
    path('organisme/supprimer/<slug>/', views.OrganismeFormationDelete.as_view(), name="supprimer_organisme"),
    path('organisme/activation/<slug>/', views.activer_of, name="activer_of"),
    path('organisme/desactivation/<slug>/', views.desactiver_of, name="desactiver_of"),
    path('formateur/creer/', views.FormateurCreate.as_view(), name="ajouter_formateur"),
    path('formateur/supprimer/<slug>/', views.FormateurDelete.as_view(), name="supprimer_formateur"),
    path('entreprises/intervenantes/creer/', views.EntrepriseIntCreate.as_view(), name="ajouter_entreprise_interv"),
    path('entreprise/intervenante/modifier/<slug>/', views.EntrepriseIntUpdate.as_view(), name="modifier_entreprise_interv"),
    path('entreprise/intervenante/supprimer/<slug>/', views.EntrepriseIntDelete.as_view(), name="supprimer_entreprise_interv"),
    path('entreprise/intervenante/activation/<slug>/', views.EntrepriseInterActivation.as_view(), name="activer_ei"),
    path('entreprise/intervenante/desactivation/<slug>/', views.desactiver_of, name="desactiver_ei"),
    path('intervenant/creer/', views.IntervenantCreate.as_view(), name="ajouter_intervenant"),
    path('intervenant/modifier/<slug>/', views.IntervenantUpdate.as_view(), name="modifier_intervenant"),
    path('intervenant/supprimer/<slug>/', views.IntervenantDelete.as_view(), name="supprimer_intervenant"),
    path('entreprise/utilisatrice/creer', views.EntrepriseUtilCreate.as_view(), name="ajouter_entreprise_util"),
    path('entreprise/utilisatrice/modifier/<slug>/', views.EntrepriseUtilUpdate.as_view(), name="modifier_entreprise_util"),
    path('entreprise/utilisatrice/supprimer/<slug>/', views.EntrepriseUtilDelete.as_view(), name="supprimer_entreprise_util"),
    path('entreprise/utilisatrice/activation/<slug>/', views.EntrepriseUtilActivation.as_view(), name="activer_eu"),
    path('evenement/creer/', views.EvenementCreate.as_view(), name="ajouter_event"),
    path('evenement/modifier/<slug>', views.EvenementUpdate.as_view(), name="modifier_event"),
    path('evenement/supprimer/<slug>', views.EvenementDelete.as_view(), name="supprimer_event"),
    path('document/creer/', views.DocumentCreate.as_view(), name="ajouter_document"),
    path('document/modifier/<slug>', views.DocumentUpdate.as_view(), name="modifier_document"),
    path('document/detail/<slug>', views.DocumentDetail.as_view(), name="detail_document"),
    path('document/supprimer/<slug>', views.DocumentDelete.as_view(), name="supprimer_document"),
    path('document/admin_liste/', views.DocumentAdminListe.as_view(), name="liste_documents_admin"),
    path('utilisateurs/liste', views.UtilisateurListe.as_view(), name="liste_utilisateurs"),
    path('utilisateurs/activation/<pk>/', views.ActivationUtilisateur.as_view(), name="activation_utilisateur"),
    path('utilisateur/activation/<pk>/', views.ActivationUtilisateur.as_view(), name="activation_utilisateur"),
    path('utilisateur/supprimer/<pk>/', views.UtilisateurDelete.as_view(), name="supprimer_utilisateur"),
]