# Generated by Django 2.0.1 on 2018-08-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mase', '0002_remove_formationsorganismes_validite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepriseintervenante',
            name='entreprise_utilisatrice',
        ),
        migrations.AddField(
            model_name='entrepriseintervenante',
            name='utilisatrices',
            field=models.ManyToManyField(related_name='intervantes', to='mase.EntrepriseUtilisatrice'),
        ),
    ]
