# Generated by Django 2.0.1 on 2019-01-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mase', '0003_auto_20180809_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervenant',
            name='code',
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='num_gtis',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
