# Generated by Django 2.0.1 on 2019-01-08 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mase', '0004_auto_20190108_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='exp_agreement',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organismeformation',
            name='exp_agreement',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
